name: CI

on:
  push:
  pull_request:

env:
  SITE_URL: https://zezulka.me

jobs:
  static-checks:
    runs-on: codeberg-medium
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm' # Speeds up npm ci

      - name: Install dependencies
        run: npm ci

      - name: Format, Lint and Typecheck
        run: |
          npm run format:check
          npm run lint
          npm run typecheck
  testing:
    runs-on: codeberg-medium
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for Testing
        run: |
          npm run last-modified
          npm run build
          npm run test:static

      - name: E2E tests
        env:
          PLAYWRIGHT_WORKERS: 2
        run: |
          npx playwright install --with-deps
          npm run test:e2e

      - name: Accessibility tests
        run: |
          npx puppeteer browsers install chrome
          npm run test:a11y:ci
  performance-and-deploy:
    runs-on: codeberg-medium
    timeout-minutes: 10
    needs: [static-checks, testing]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Initial Build & Performance tests
        run: |
          npm run last-modified
          npm run build
          npm run test:static
          npm run size:check
          npm run lighthouse:ci

      - name: Extract Lighthouse report & Rebuild
        run: |
          node --experimental-strip-types scripts/extract-lighthouse.ts
          npm run build
          npm run test:static
          npm run size:check

      - name: Publish to custom domain
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/git-pages@v2
        with:
          site: https://zezulka.me/
          token: ${{ forge.token }}
          source: dist/
