import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { buildCsp } from './csp.mjs';
import { computeHash } from './generate-csp-hash.mjs';

/* eslint-disable no-console */

const ROOT_DIR = process.cwd();
const DATA_DIR = join(ROOT_DIR, 'src/data');
const SCRIPT_PATH = join(ROOT_DIR, 'src/scripts/theme-bootstrap.txt');
const HEADERS_TEMPLATE = join(DATA_DIR, '_headers.template');
const HEADERS_OUTPUT = join(ROOT_DIR, 'public/_headers');
const CSP_DATA_OUTPUT = join(DATA_DIR, 'csp.ts');

try {
  // 1. Compute hash
  const hash = computeHash(SCRIPT_PATH);
  console.log(`Computed CSP hash: ${hash}`);

  // 2. Build CSP
  const csp = buildCsp({ themeScriptHash: hash });

  // 3. Generate _headers
  const headersTemplate = readFileSync(HEADERS_TEMPLATE, 'utf8');
  const headersContent = headersTemplate.replace('{{CSP}}', csp);
  writeFileSync(HEADERS_OUTPUT, headersContent);
  console.log(`Generated public/_headers with CSP`);

  // 4. Emit src/data/csp.ts
  const scriptContent = readFileSync(SCRIPT_PATH, 'utf8');
  const cspTsContent = `/**
 * AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
 * Generated by scripts/generate-csp.ts
 */

export const THEME_BOOTSTRAP_HASH = '${hash}';
export const THEME_BOOTSTRAP_SCRIPT = \`${scriptContent.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;
export const SITE_CSP = "${csp}";
`;
  mkdirSync(DATA_DIR, { recursive: true });
  writeFileSync(CSP_DATA_OUTPUT, cspTsContent);
  console.log(`Generated src/data/csp.ts`);
} catch (error) {
  console.error('Error generating CSP assets:', error);
  process.exit(1);
}
